### ISSUE TITLE
Crash when attempting to sync and Network Permission is denied

### ISSUE THREAD

**Issue by realbiz21** [standardnotes/mobile#491]
I am using Standard Notes version 3.6.23 from F-Droid on a GrapheneOS Pixel 4a.

GrapheneOS includes a "Network" permission so that apps can be denied from accessing the network.

When the Network permission is allowed, I logged into my Standard Notes account and saw my notes. Made updates. I saw it syncing correctly.

Then I disabled the Network Permission to Standard Notes [App Info, Permissions, Network=Denied]. I went back to the app. The main screen came up. After about 1 second it said "Unable to sync" [which is expected], but then the app crashed. This is the stack trace:

```
09-23 20:36:02.233  4370  4415 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
09-23 20:36:02.233  4370  4415 E AndroidRuntime: Process: com.standardnotes, PID: 4370
09-23 20:36:02.233  4370  4415 E AndroidRuntime: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:150)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.Dns$1.lookup(Dns.java:40)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
09-23 20:36:02.233  4370  4415 E AndroidRuntime: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at libcore.io.Linux.android_getaddrinfo(Native Method)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)

09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        ... 26 more
09-23 20:36:02.233  4370  4415 E AndroidRuntime: Caused by: android.system.ErrnoException: android_getaddrinfo failed: EPERM (Operation not permitted)
09-23 20:36:02.233  4370  4415 E AndroidRuntime:        ... 31 more
09-23 20:36:02.237   430  4422 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-23 20:36:02.252   430   479 W ActivityTaskManager:   Force finishing activity com.standardnotes/.MainActivity
```

**Comment by JaspalSuri** [comment]
Hi @realbiz21, sorry to hear that. It looks the app currently doesn't have a way to handle being denied permission to access a network. We'll keep note of this issue, but it won't be a high priority to fix since it wouldn't make sense for a user to sign in and then deny the app access to one's network (especially since one can temporarily use airplane mode to launch the app and sign out if needed). Hopefully the team behind GrapheneOS will provide some documentation regarding this in the future ([as mentioned in the other thread](https://github.com/GrapheneOS/grapheneos.org/issues/258#issuecomment-926611391)).

**Comment by realbiz21** [comment]
I concur with the priority assessment @JaspalSuri; though it crashes in the given scenario, it does not prevent the app from working properly once Network permission is re-enabled, nor have I seen any loss of data due to this issue.

To give further background on the use case:

Sometimes I am using a network which I do not want the presence of some connections to be known to the network, but I do not want to fully block network access to the OS or other apps. In addition, I may still need to update notes in Standard Notes, just in an offline-mode.

And if I am being totally honest, all my apps have Network Permission denied unless I am actively using them.

As noted in the GrapheneOS issue, I do hope the GrapheneOS team can clarify or improve compatibility so that I can submit a simple pull request to Standard Notes, so I fully understand if this issue is sort of bounced around, but I thank you for keeping note of it and will keep you updated.

**Comment by realbiz21** [comment]
This is no longer an issue in Standard Notes.

GrapheneOS has implemented some fixes that avoid a crash.

I believe the resolution from GrapheneOS from the [2021121602 release notes](https://grapheneos.org/releases#2021121602) explains why:

> remove special case of throwing SecurityException for socket errors caused by EACCES/EPERM as a debugging aid since it causes compatibility issues when the Network (INTERNET) permission is revoked

This may have been from GrapheneOS/os-issue-tracker#560.

I request this issue to be closed since it was given an external-issue tag and an external resolution has been provided.
